In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar
from scipy.interpolate import PchipInterpolator
from scipy.integrate import quad
from scipy.stats import bootstrap
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

# Level-1 Trigger (CMS)

In [2]:
egamma = pd.read_csv("l1t_data/egamma.csv")
tau = pd.read_csv("l1t_data/isolated tau.csv")
jet_energy = pd.read_csv("l1t_data/jet energy.csv")
muon = pd.read_csv("l1t_data/single muon.csv")

In [3]:
rates = pd.read_excel("l1t_data/trigger_rates.xlsx")

In [4]:
triggers = ["Jet", "Muon", "EGamma", "Tau"]
rejection_ratio = 400
jet_rate = rates["Jet Rate"][0] 
muon_rate = rates["Muon Rate"][0] 
egamma_rate = rates["Egamma Rate"][0] 
tau_rate = rates["Tau Rate"][0] 
all_rates = [jet_rate, muon_rate, egamma_rate, tau_rate]

In [5]:
fig = go.Figure()
fig.add_bar(x = triggers, y = all_rates)
fig.update_layout(width = 800, height = 600)

In [6]:
exp_dist = lambda x, l: l * np.exp(-1 * l * x) * (x > 0)

In [7]:
exp_cdf = lambda x, l: 1 - np.exp(-l * x)

In [8]:
exp_generator = lambda p, l: (-1 / l) * np.log(1 - p)

In [9]:
xs = np.linspace(0.01, 5.0, 101)
fig = go.Figure()
fig.add_scatter(x = xs, y = exp_dist(xs, 1.5), name = "PDF")
fig.add_scatter(x = xs, y = exp_cdf(xs, 1.5), name = "CDF")
fig.update_layout(width = 800, height = 600)

In [10]:
data_range = lambda x: np.linspace(np.min(x), np.max(x), 101)

In [11]:
egamma_spl = PchipInterpolator(egamma["x"], egamma[" y"])

In [12]:
egamma_xs = data_range(egamma["x"])

In [13]:
egamma_rate

np.float64(0.444)

# Fit to EGamma L1T

In [14]:
#fit to muon - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
egamma_fit = lambda l: np.abs(egamma_rate - quad(lambda x: exp_dist(x, l) * egamma_spl(x), np.min(egamma_xs), np.max(egamma_xs))[0])

In [15]:
egamma_soln = minimize_scalar(egamma_fit, bounds = [0.00, 0.40], method="bounded")
egamma_l = egamma_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_89811/3527769200.py:2: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [16]:
egamma_soln

 message: Solution found.
 success: True
  status: 0
     fun: 1.6358825408624433e-05
       x: 0.02585292794736181
     nit: 18
    nfev: 18

In [17]:
egamma_threshold = 30
egamma_ideal = lambda x: 1.0 * (x > egamma_threshold)

In [18]:
fig = go.Figure()
fig.add_scatter(x = egamma["x"], y = egamma[" y"], name="Data")
fig.add_scatter(x = egamma_xs, y = egamma_spl(egamma_xs), name="Interpolation")
fig.add_scatter(x = egamma_xs, y = egamma_ideal(egamma_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = egamma_xs, y = 1.0 - exp_cdf(egamma_xs, egamma_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "e-gamma L1T efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )
fig.update_xaxes(type = "log")

In [19]:
fig = go.Figure()
fig.add_scatter(x = egamma["x"], y = egamma[" y"], name="Data")
fig.add_scatter(x = egamma_xs, y = egamma_spl(egamma_xs), name="Interpolation")
fig.add_scatter(x = egamma_xs, y = egamma_ideal(egamma_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = egamma_xs, y = 1.0 - exp_cdf(egamma_xs, egamma_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "e-gamma L1T efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )


## Fit to Tau 

In [20]:
tau_xs = data_range(tau["x"])
tau_spl = PchipInterpolator(tau["x"], tau[" y"])

In [21]:
#fit to tau - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
tau_fit = lambda l: np.abs(tau_rate - quad(lambda x: exp_dist(x, l) * tau_spl(x), 0, 100)[0])

In [22]:
tau_threshold = 38
tau_ideal = lambda x: 1.0 * (x > tau_threshold)

In [23]:
tau_soln = minimize_scalar(tau_fit)
tau_l = tau_soln.x

In [24]:
tau_soln

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 1.378231251347728e-09
       x: 0.04457408261926413
     nit: 31
    nfev: 34

In [25]:
tau_l

np.float64(0.04457408261926413)

In [26]:
fig = go.Figure()
fig.add_scatter(x = tau["x"], y = tau[" y"], name = "Data")
fig.add_scatter(x = tau_xs, y = tau_spl(tau_xs), name = "Interpolation")
fig.add_scatter(x = tau_xs, y = tau_ideal(tau_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = tau_xs, y = 1.0 - exp_cdf(tau_xs, tau_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Tau L1T Efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )
fig.update_xaxes(type = "linear")

## Fit to Jets

In [27]:
jet_xs = data_range(jet_energy["x"])
jet_spl = PchipInterpolator(jet_energy["x"], jet_energy[" y"])

In [28]:
jet_fit = lambda l: np.abs(jet_rate - quad(lambda x: exp_dist(x, l) * jet_spl(x), 0, np.max(jet_xs))[0])
jet_soln = minimize_scalar(jet_fit, bounds = [0.000, 0.40], method="bounded")
jet_l = jet_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_89811/2457454635.py:1: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [29]:
jet_soln

 message: Solution found.
 success: True
  status: 0
     fun: 0.00010411688622924409
       x: 0.0034652456666858103
     nit: 19
    nfev: 19

In [30]:
jet_l

np.float64(0.0034652456666858103)

In [31]:
jet_threshold = 320
jet_ideal = lambda x: 1.0 * (x > jet_threshold)

In [32]:
fig = go.Figure()
fig.add_scatter(x = jet_energy["x"], y = jet_energy[" y"], name = "Data")
fig.add_scatter(x = jet_xs, y = jet_spl(jet_xs), name = "Interpolation")
fig.add_scatter(x = jet_xs, y = jet_ideal(jet_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = jet_xs, y = 1.0 - exp_cdf(jet_xs, jet_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Jet Energy L1T Efficiency",
                  xaxis_title = "Momentum (GeV)"
                  )
fig.update_xaxes(type = "linear")

## Fit to Muon

In [33]:
muon_xs = data_range(muon["x"])
muon_spl = PchipInterpolator(muon["x"], muon[" y"])

In [34]:
#fit to muon - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
muon_fit = lambda l: np.abs(muon_rate - quad(lambda x: exp_dist(x, l) * muon_spl(x), 0, np.max(muon_xs))[0])
muon_soln = minimize_scalar(muon_fit, bounds = [0.00, 0.60], method="bounded")
muon_l = muon_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_89811/304049715.py:2: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [35]:
muon_soln

 message: Solution found.
 success: True
  status: 0
     fun: 1.1561599530418576e-05
       x: 0.05513915504855077
     nit: 18
    nfev: 18

In [36]:
muon_l

np.float64(0.05513915504855077)

In [37]:
muon_threshold = 22
muon_ideal = lambda x: 1.0 * (x > muon_threshold)

In [38]:
fig = go.Figure()
fig.add_scatter(x = muon["x"], y = muon[" y"], name = "data")
fig.add_scatter(x = muon_xs, y = muon_spl(muon_xs), name = "Interpolation")
fig.add_scatter(x = muon_xs, y = muon_ideal(muon_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = muon_xs, y = 1.0 - exp_cdf(muon_xs, muon_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Single Muon L1T Efficiency",
                  xaxis_title = "Momentum (GeV)"
                  )
fig.update_xaxes(type = "linear")

# Modeling Skill

In [39]:
#find the percentile of measurements above threshold
egamma_prctile = exp_cdf(egamma_threshold, egamma_l)
jet_prctile = exp_cdf(jet_threshold, jet_l)
muon_prctile = exp_cdf(muon_threshold, muon_l)
tau_prctile = exp_cdf(tau_threshold, tau_l) 

In [40]:
thresholds = np.array([jet_threshold, muon_threshold, egamma_threshold, tau_threshold])

In [41]:
prctiles = np.array([jet_prctile, muon_prctile, egamma_prctile, tau_prctile])

In [42]:
prctiles

array([0.67007127, 0.70271423, 0.53956696, 0.8161831 ])

In [43]:
def generate_null():
    p = np.random.uniform(size=(4)) * prctiles
    jet = exp_generator(p[0], jet_l)
    muon = exp_generator(p[1], muon_l)
    egamma = exp_generator(p[2], egamma_l)
    tau = exp_generator(p[3], tau_l)
    

    e = np.array([jet, muon, egamma, tau])
    z = np.array([jet_spl(e[0]),
                muon_spl(e[1]),
                egamma_spl(e[2]),
                tau_spl(e[3])])
    
    res = np.stack((e, z))
    
    return res


In [44]:
muon_spl(75)

array(0.94208706)

In [45]:
null_evt = generate_null()

In [46]:
n_samples = int(1e4)

In [47]:
null_evts = np.stack([generate_null() for i in range(n_samples)])

In [48]:
null_evts.shape

(10000, 2, 4)

In [49]:
null_z = np.sum(null_evts, axis=2)[:,1]

In [50]:
np.std(null_z)

np.float64(0.29124276474648925)

In [51]:
triggers

['Jet', 'Muon', 'EGamma', 'Tau']

In [52]:
prctiles

array([0.67007127, 0.70271423, 0.53956696, 0.8161831 ])

In [53]:
evt_rng = np.random.default_rng()

In [54]:
trigger_rates = rates["Proportion"]

In [55]:
trigger_choice = lambda: evt_rng.choice(np.arange(len(trigger_rates)), 1, p = trigger_rates)[0]

In [56]:
rates.iloc[trigger_choice()]

Percentage            12.700
Proportion             0.127
Jet / Jet energy       0.000
Muon                   0.000
Egamma                 0.000
Tau                    1.000
Jet proportions        0.000
Muon proportions       0.000
Egamma proportions     0.000
Tau proportions        0.127
Jet Rate                 NaN
Muon Rate                NaN
Egamma Rate              NaN
Tau Rate                 NaN
Jet Threshold            NaN
Muon Threshold           NaN
Egamma Threshold         NaN
Tau Threshold            NaN
Name: 9, dtype: float64

In [57]:
def generate_positive():
    #select a trigger outcome with rates proportional to those recorded
    outcome_idx = trigger_choice()
    outcome = rates.iloc[outcome_idx]

    #determine the triggers for that outcome
    trig_egamma = outcome["Egamma"]
    trig_jet = outcome["Jet / Jet energy"]
    trig_muon = outcome["Muon"]
    trig_tau = outcome["Tau"]

    triggers = np.array([trig_jet, trig_muon, trig_egamma, trig_tau])

    #generate particle energies from the distributions based on whether or not they're above trigger levels
    def transform_p(prctile, outcome):
        p = np.random.uniform()
        if outcome == 1.0:
            #generate an event above the trigger threshold
            return p * (1 - prctile) + prctile
        else:
            #generate an event below the trigger threshold
            return p * prctile
        
    p_jet = transform_p(jet_prctile, trig_jet)
    p_muon = transform_p(muon_prctile, trig_muon)
    p_egamma = transform_p(egamma_prctile, trig_egamma)
    p_tau = transform_p(tau_prctile, trig_tau)

    jet = exp_generator(p_jet, jet_l)
    muon = exp_generator(p_muon, muon_l)
    egamma = exp_generator(p_egamma, egamma_l)
    tau = exp_generator(p_tau, tau_l)

    e = np.array([jet, muon, egamma,  tau,])
    z = np.array([jet_spl(e[0]),
                  muon_spl(e[1]),
                  egamma_spl(e[2]),
                  tau_spl(e[3]),
                  ])
    
    res = np.stack((e, z))
    
    return res


In [58]:
pos_evt = generate_positive()

In [59]:
pos_evt

array([[7.83177141e+00, 3.29739704e+01, 1.40277350e+01, 8.41984027e+00],
       [0.00000000e+00, 9.36991057e-01, 1.65812546e-02, 3.82153969e-03]])

In [60]:
thresholds

array([320,  22,  30,  38])

In [61]:
pos_evt[1,:]

array([0.        , 0.93699106, 0.01658125, 0.00382154])

In [62]:
pos_evts = np.stack([generate_positive() for i in range(n_samples)])

In [63]:
pos_evts.shape

(10000, 2, 4)

In [64]:
pos_z = np.sum(pos_evts, axis=2)[:,1]

## determine statistics

In [65]:
def generate_exp():
    p = np.random.uniform(size=(4))
    jet = exp_generator(p[0], jet_l)
    muon = exp_generator(p[1], muon_l)
    egamma = exp_generator(p[2], egamma_l)
    tau = exp_generator(p[3], tau_l)
    
    e = np.array([jet, muon, egamma, tau])
    z = np.array([jet_spl(e[0]),
                muon_spl(e[1]),
                egamma_spl(e[2]),
                tau_spl(e[3])])
    
    res = np.stack((e, z))
    
    return res


In [66]:
exp_dist = np.stack([generate_exp() for i in range(n_samples)])

In [67]:
exp_dist.shape

(10000, 2, 4)

In [68]:
n_samples

10000

In [69]:
def order_test(null_dist, pos_dist, selection: int = 401):
    idx_null = np.random.choice(np.arange(n_samples), selection - 1)
    idx_pos = np.random.choice(np.arange(n_samples), 1)

    select = lambda x, idx: np.sum(x[idx,1,:], axis=1)
    null_scores = select(null_dist, idx_null)
    pos_score = select(pos_dist, idx_pos)

    if np.all(pos_score > null_scores):
        confusion = np.array([[selection - 1, 0], [0, 1]])
    else:
        confusion = np.array([[selection - 2, 1], [1, 0]])

    return confusion


In [70]:
z = order_test(null_evts, pos_evts, 400)

In [71]:
run_test = lambda s: order_test(null_evts, pos_evts, s)

In [72]:
perf = np.sum([run_test(400) for i in range(2000)], axis=0)

In [73]:
perf

array([[796588,   1412],
       [  1412,    588]])

In [74]:
1428 / (796572 + 1428)

0.0017894736842105263

In [75]:
stats = lambda c: c / np.sum(c, axis=0)

In [76]:
stats(perf)

array([[0.99823058, 0.706     ],
       [0.00176942, 0.294     ]])

In [77]:
stats(np.sum([run_test(100) for i in range(2000)], axis=0))

array([[0.99400505, 0.5935    ],
       [0.00599495, 0.4065    ]])

In [78]:
exp_z = np.sum(exp_dist[:,1,:], axis=1)

In [79]:
px.histogram(exp_z, log_y = True)