In [1]:
from classifier import *

In [2]:
import plotly.express as px

In [3]:
# dummy classifier test

In [4]:
dc = DummyClassifier()
dc([600, 400], 1.0)

array([[  0,   0],
       [600, 400]])

In [5]:
# gaussian classifier test

In [6]:
gc = GaussianClassifier(3.0)

In [7]:
gc([1000, 10], 0.99)

array([[996,   3],
       [  3,   6]])

In [8]:
gc.threshold

2.669041266209834

In [9]:
gc.tn

0.9961965948124544

In [10]:
gc.fp

0.0038034051875456276

In [11]:
gc.fn

0.3703378281326751

In [12]:
gc.error_matrix

array([[0.99619659, 0.37033783],
       [0.00380341, 0.62966217]])

In [13]:
o = gc([1000, 100], 0.99)

In [14]:
o

array([[999,  89],
       [  0,  10]])

In [15]:
get_rejected(o)

array([999,  89])

In [16]:
get_passed(o)

array([ 0, 10])

In [17]:
# L1T test

In [18]:
l1 = L1TClassifier()

/Users/wilkie/code/system_flow/classifier.py:197: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [19]:
l1.egamma_l

0.02585292794736181

In [20]:
l1.jet_l

0.0021968083767679625

In [21]:
l1.muon_l

0.04166357056582804

In [22]:
l1.tau_l

0.01586962977254491

In [23]:
l1.null_samples

array([[[1.96128427e+02, 7.70843765e+00, 3.93625310e+00, 2.41440623e+01],
        [2.01410287e-02, 1.09506922e-02, 0.00000000e+00, 4.33797302e-02]],

       [[1.37930948e+02, 8.57959418e+00, 1.60295978e+01, 2.46185336e+01],
        [4.81493695e-05, 1.51569458e-02, 1.82145500e-02, 4.66871640e-02]],

       [[1.33846838e+02, 1.90622147e+01, 1.76849605e+01, 2.51921714e+01],
        [7.48564200e-06, 5.92908261e-01, 1.91668958e-02, 5.19753411e-02]],

       ...,

       [[9.04057248e+01, 1.99670063e+01, 2.71945755e+01, 2.13877848e+01],
        [0.00000000e+00, 6.67316316e-01, 7.39954725e-02, 2.64978984e-02]],

       [[2.51925876e+02, 1.66526667e+00, 5.27585620e+00, 2.47948267e+01],
        [1.63197057e-01, 3.41740910e-03, 4.58335818e-05, 4.81590203e-02]],

       [[6.20292508e+01, 8.66476493e+00, 9.08865172e+00, 1.41017509e+01],
        [0.00000000e+00, 1.56532752e-02, 6.39289310e-03, 1.07734435e-02]]])

In [24]:
l1.pos_samples

array([[[1.82278280e+02, 4.02936308e+01, 1.30000774e+00, 1.84529954e+01],
        [9.19004632e-03, 9.42046856e-01, 0.00000000e+00, 1.83232833e-02]],

       [[1.13685188e+02, 4.30623026e+01, 3.65622373e+00, 1.95448937e+01],
        [0.00000000e+00, 9.43279901e-01, 0.00000000e+00, 2.05079121e-02]],

       [[4.04724448e+02, 1.87245384e+01, 2.21449594e+01, 7.80972248e+00],
        [9.89849320e-01, 5.61461300e-01, 2.16690610e-02, 3.27880812e-03]],

       ...,

       [[1.73255241e+01, 2.94302431e+00, 4.88079213e+01, 1.78502197e+01],
        [0.00000000e+00, 3.39791117e-04, 9.55127291e-01, 1.71663779e-02]],

       [[8.62981340e+02, 5.77573364e+00, 1.15239605e+02, 2.09561993e+01],
        [9.93819530e-01, 3.60627723e-03, 9.83250552e-01, 2.45366319e-02]],

       [[3.29187584e+02, 6.16383098e+00, 1.06768886e+01, 1.39347606e+01],
        [9.01760242e-01, 4.84748712e-03, 1.01719159e-02, 1.05213542e-02]]])

In [25]:
n_ecdf = ecdf(l1.null_scores)

In [26]:
n_ecdf.cdf.evaluate(0.26)

array(0.5501)

In [27]:
l1.solve_reduction([4000, 10], 0.99)  

In [50]:
from scipy.stats import gaussian_kde

In [60]:
from scipy.integrate import cumulative_trapezoid

In [48]:
px.histogram(x = l1.pos_scores)

In [ ]:
pos_kde = gaussian_kde(l1.pos_scores)

In [63]:
xpts = np.linspace(0.0, 5.0, 1001)
ypts = pos_kde.evaluate(xpts)
ycdf = cumulative_trapezoid(ypts, xpts, initial=0)
px.scatter(x = xpts, y = ypts)

In [64]:
px.scatter(x = xpts, y = ycdf)

In [49]:
px.histogram(x = l1.null_scores)

In [56]:
neg_kde = gaussian_kde(l1.null_scores)

In [65]:
xpts = np.linspace(0.0, 5.0, 1001)
ypts = neg_kde.evaluate(xpts)
ycdf = cumulative_trapezoid(ypts, xpts, initial=0)
px.scatter(x = xpts, y = ypts)

In [66]:
xpts = np.linspace(0.0, 4.2, 1001)
px.scatter(x = xpts, y = ycdf)

In [28]:
l1.threshold

1.324268798394196

In [29]:
l1.error_matrix

array([[0.9909, 0.6151],
       [0.0091, 0.3849]])

In [30]:
l1.skill_boost = 5.0

In [31]:
l1.solve_reduction([4000, 10], 0.99)  

In [32]:
l1.threshold

1.3569647509057297

In [33]:
l1.error_matrix

array([[0.9924, 0.    ],
       [0.0076, 1.    ]])

In [34]:
cont = [4000, 10] * l1.error_matrix

In [35]:
np.sum(get_rejected(cont))

3969.6

In [36]:
np.sum(get_passed(cont))

40.400000000000205

In [37]:
ps = np.linspace(0, 1.0, 201)

In [38]:
l1.scores(1.3)

0.9874314214463841

In [39]:
sol = minimize_scalar(lambda x: np.abs(0.99 - l1.scores(x)), bounds = (0.0, 6.0), method="bounded")

In [40]:
sol

 message: Solution found.
 success: True
  status: 0
     fun: 0.0075062344139651405
       x: 3.7082089871747406
     nit: 29
    nfev: 29

In [41]:
sol.x

3.7082089871747406

In [42]:
xs = np.linspace(0.0, 3.0, 201)

In [43]:
px.scatter(x = xs, y = l1.scores(xs), log_y=True)

In [44]:
0.99 - l1.scores(l1.threshold)

7.48129675810505e-05

In [45]:
l1.threshold

1.3569647509057297

In [46]:
l1.error_matrix

array([[0.9924, 0.    ],
       [0.0076, 1.    ]])

In [47]:
l1([400*10,     10])

TypeError: L1TClassifier.__call__() missing 1 required positional argument: 'reduction'

In [ ]:
4010 / 69

58.11594202898551

In [ ]:
l1.error_matrix

array([[0.98409371, 0.38072391],
       [0.01590629, 0.61927609]])