In [1]:
from classifier import *

In [2]:
import plotly.express as px

In [3]:
# dummy classifier test

In [4]:
dc = DummyClassifier()
dc([600, 400])

array([[  0,   0],
       [600, 400]])

In [5]:
# gaussian classifier test

In [6]:
gc = GaussianClassifier(99 / 100, 3.0)

In [7]:
gc([1000, 10])

array([[996,   3],
       [  3,   6]])

In [8]:
gc.threshold

2.669043039901781

In [9]:
gc.tn

0.9961966148977294

In [10]:
gc.fp

0.003803385102270629

In [11]:
gc.fn

0.37033849802260643

In [12]:
gc.error_matrix

array([[0.99619661, 0.3703385 ],
       [0.00380339, 0.6296615 ]])

In [13]:
o = gc([1000, 100])

In [14]:
o

array([[999,  89],
       [  0,  10]])

In [15]:
get_rejected(o)

array([999,  89])

In [16]:
get_passed(o)

array([ 0, 10])

In [17]:
# L1T test

In [18]:
l1 = L1TClassifier(99/100)

/Users/wilkie/code/system_flow/classifier.py:204: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [19]:
l1.egamma_l

0.02585292794736181

In [20]:
l1.jet_l

0.0021968083767679625

In [21]:
l1.muon_l

0.04166357056582804

In [22]:
l1.tau_l

0.01586962977254491

In [23]:
l1.null_samples

array([[[8.53639947e+01, 1.02831203e+01, 3.25999533e-01, 1.60913748e+01],
        [0.00000000e+00, 3.14852738e-02, 0.00000000e+00, 1.39931235e-02]],

       [[2.96053253e+00, 2.01249578e+00, 2.27471447e+01, 1.32322749e+01],
        [0.00000000e+00, 2.23850993e-03, 2.21413738e-02, 9.49198677e-03]],

       [[1.58509211e+02, 8.99954435e+00, 9.43507651e+00, 1.13686446e+01],
        [7.90705624e-04, 1.78436872e-02, 7.12912246e-03, 7.00730326e-03]],

       ...,

       [[1.30168512e+02, 1.47301889e+01, 3.41128417e+00, 3.79300016e+01],
        [0.00000000e+00, 2.60152141e-01, 0.00000000e+00, 4.99707199e-01]],

       [[1.36704839e+02, 5.29195061e+00, 8.15681304e+00, 2.52011293e+00],
        [3.22300949e-05, 2.27587209e-03, 4.34651650e-03, 3.00717951e-04]],

       [[2.90993964e+02, 1.05422360e+01, 3.15217991e+00, 1.40231156e+01],
        [5.30074755e-01, 3.56096188e-02, 0.00000000e+00, 1.06543825e-02]]])

In [24]:
l1.pos_samples

array([[[6.75189351e+01, 9.43071265e+00, 8.11340313e+01, 1.49369755e+01],
        [0.00000000e+00, 2.13627491e-02, 9.78215894e-01, 1.20766566e-02]],

       [[1.34204450e+02, 6.73302520e+00, 1.04253970e+01, 1.10303299e+02],
        [9.63483087e-06, 6.90755944e-03, 9.50922005e-03, 9.92869956e-01]],

       [[3.11354418e+02, 5.92300156e+01, 5.09943001e+01, 1.63110675e+01],
        [7.75975847e-01, 9.42952014e-01, 9.58687074e-01, 1.43728604e-02]],

       ...,

       [[1.18102844e+03, 2.90039999e+00, 2.30946803e+01, 1.09598183e+01],
        [9.93819530e-01, 3.89046039e-04, 2.25835572e-02, 6.51059369e-03]],

       [[3.03953960e+02, 3.00251204e+01, 1.44411633e+01, 3.60849404e+01],
        [6.99006216e-01, 9.32845863e-01, 1.69872684e-02, 3.93701593e-01]],

       [[2.39674466e+02, 1.96278087e+01, 1.00253577e+02, 2.14592178e+01],
        [1.08592048e-01, 6.41411613e-01, 9.81407606e-01, 2.67835409e-02]]])

In [25]:
from scipy.stats import permutation_test

In [26]:
nz = np.sum(l1.null_samples[:,1,:], axis=1)

In [27]:
pz = np.sum(l1.pos_samples[:,1,:], axis=1)

In [28]:
px.histogram(nz)

In [29]:
px.histogram(pz)

In [30]:
t = np.reshape(pz, (1, -1)) > np.reshape(nz, (-1,1))

In [31]:
t.shape

(10000, 10000)

In [32]:
np.mean(t)

0.97525996

In [33]:
def order_test(null_samples, pos_samples):
    score = lambda x: np.sum(x[:,1,:], axis=1)
    null_scores = score(null_samples)
    pos_scores = score(pos_samples)

    p = np.mean(np.reshape(pos_scores, (1, -1)) > np.reshape(null_scores, (-1,1)))
    error = 1 - p
    confusion = np.array([[p, error], [error, p]])

    return confusion

In [34]:
ordering_error = order_test(l1.null_samples, l1.pos_samples)

In [35]:
ordering_error

array([[0.97525996, 0.02474004],
       [0.02474004, 0.97525996]])

In [36]:
inp =  [39992495,     7504]

In [37]:
ordering = inp *ordering_error

In [38]:
ordering

array([[3.90030791e+07, 1.85649260e+02],
       [9.89415926e+05, 7.31835074e+03]])

In [39]:
get_passed(ordering)

array([989415.9259998 ,   7318.35073984])

In [40]:
n_out = l1.reduction * np.sum(inp)

In [41]:
n_out / np.sum(inp)

0.99

In [42]:
n_out

39599999.01

In [43]:
np.sum(ordering, axis=1)

array([39003264.72326037,   996734.27673964])

In [44]:
predictions = np.sum(ordering, axis=1)

In [45]:
predictions

array([39003264.72326037,   996734.27673964])

In [46]:
n_out / predictions[1]

39.72974536356202

In [47]:
get_passed(o)

array([ 0, 10])

In [48]:
o[1,:]

array([ 0, 10])

In [49]:
np.sum(o, axis=1)

array([1088,   10])

In [50]:
np.sum(o)

1098

In [51]:
predictions[1] / predictions[0]

0.025555149903777576

In [52]:
cutoff = (n_out - predictions[1]) / predictions[0]

In [53]:
cutoff

0.989744448500962

In [54]:
accepted = get_rejected(ordering) * cutoff

In [55]:
accepted

array([3.86030810e+07, 1.83745325e+02])

In [56]:
ordering

array([[3.90030791e+07, 1.85649260e+02],
       [9.89415926e+05, 7.31835074e+03]])

In [57]:
contingency  = np.stack((get_rejected(ordering) - accepted, get_passed(ordering) + accepted), axis=0)

In [58]:
contingency

array([[3.99998086e+05, 1.90393555e+00],
       [3.95924969e+07, 7.50209606e+03]])

In [59]:
contingency / np.sum(contingency, axis=0)

array([[1.00018287e-02, 2.53722754e-04],
       [9.89998171e-01, 9.99746277e-01]])

In [60]:
l1.reduction

0.99

In [66]:
l1.reduction = 0.99

In [67]:
l1([39992495,     7504])

array([[  399998,        1],
       [39592496,     7502]])

In [68]:
l1.error_matrix

array([[1.00018287e-02, 2.53722754e-04],
       [9.89998171e-01, 9.99746277e-01]])