In [1]:
from classifier import *

In [2]:
import plotly.express as px

In [3]:
# dummy classifier test

In [4]:
dc = DummyClassifier()
dc([600, 400])

array([[  0,   0],
       [600, 400]])

In [5]:
# gaussian classifier test

In [6]:
gc = GaussianClassifier(99 / 100, 3.0)

In [7]:
gc([1000, 10])

array([[996,   3],
       [  3,   6]])

In [8]:
gc.threshold

2.669041266209834

In [9]:
gc.tn

0.9961965948124544

In [10]:
gc.fp

0.0038034051875456276

In [11]:
gc.fn

0.3703378281326751

In [12]:
gc.error_matrix

array([[0.99619659, 0.37033783],
       [0.00380341, 0.62966217]])

In [13]:
o = gc([1000, 100])

In [14]:
o

array([[999,  89],
       [  0,  10]])

In [15]:
get_rejected(o)

array([999,  89])

In [16]:
get_passed(o)

array([ 0, 10])

In [17]:
# L1T test

In [18]:
l1 = L1TClassifier(99/100)

/Users/wilkie/code/system_flow/classifier.py:210: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [19]:
l1.egamma_l

0.02585292794736181

In [20]:
l1.jet_l

0.0021968083767679625

In [21]:
l1.muon_l

0.04166357056582804

In [22]:
l1.tau_l

0.01586962977254491

In [23]:
l1.null_samples

array([[[2.12132548e+02, 2.16936962e+01, 2.56929552e+01, 1.13814671e+01],
        [3.86016284e-02, 7.94308113e-01, 3.81316123e-02, 7.02316545e-03]],

       [[2.23396392e+02, 5.85508583e+00, 2.79406494e+01, 2.50344828e+01],
        [6.20938782e-02, 3.84817697e-03, 1.07077027e-01, 5.03868688e-02]],

       [[2.58745157e+02, 1.22224135e+01, 1.76849578e+01, 2.19815846e+01],
        [2.08251023e-01, 1.11139452e-01, 1.91668945e-02, 2.88695453e-02]],

       ...,

       [[1.19187144e+00, 1.23800703e+00, 2.00479770e+01, 2.41570004e+01],
        [0.00000000e+00, 5.24789681e-03, 2.04487887e-02, 4.34609494e-02]],

       [[2.47938443e+02, 1.15700880e+01, 1.32872999e+01, 2.79150326e+01],
        [1.42017037e-01, 7.99881954e-02, 1.56943139e-02, 8.28059839e-02]],

       [[2.27642600e+02, 1.19500562e+00, 2.33719201e+00, 7.65064568e+00],
        [7.28517102e-02, 5.45619071e-03, 0.00000000e+00, 3.14395043e-03]]])

In [24]:
l1.pos_samples

array([[[2.13671077e+02, 1.96946414e+01, 3.90575483e+00, 4.60031562e+01],
        [4.09288248e-02, 6.46664550e-01, 0.00000000e+00, 8.19038592e-01]],

       [[1.29898618e+03, 3.95078351e+01, 1.68617657e+02, 1.26253547e+02],
        [9.93819530e-01, 9.42046856e-01, 9.87843693e-01, 9.86651349e-01]],

       [[1.99877641e+02, 9.73753451e+00, 1.65205127e+01, 8.40229926e+01],
        [2.39766774e-02, 2.44625139e-02, 1.85318479e-02, 9.92148192e-01]],

       ...,

       [[1.32071779e+02, 3.35250617e+01, 1.02493708e+00, 7.85061039e+00],
        [8.26885049e-07, 9.37760197e-01, 0.00000000e+00, 3.31391615e-03]],

       [[5.76423563e+02, 5.48966714e+01, 4.20444032e+01, 2.13754639e+02],
        [9.92609703e-01, 9.41876851e-01, 9.41971756e-01, 7.55949620e-01]],

       [[2.15176334e+01, 9.87486643e+00, 4.11457023e+01, 3.12469107e+01],
        [0.00000000e+00, 2.60361114e-02, 9.39941750e-01, 1.39510021e-01]]])

In [25]:
n_ecdf = ecdf(l1.null_scores)

In [26]:
n_ecdf.cdf.evaluate(0.26)

array(0.5488)

In [27]:
l1.solve_reduction([4000, 10])

In [28]:
l1.reduction

0.99

In [30]:
l1.threshold

1.3250539830050259

In [31]:
l1.error_matrix

array([[0.9909, 0.6205],
       [0.0091, 0.3795]])

In [33]:
cont = [4000, 10] * l1.error_matrix

In [36]:
np.sum(get_rejected(cont))

3969.805

In [35]:
np.sum(get_passed(cont))

40.19499999999999

In [36]:
ps = np.linspace(0, 1.0, 201)

In [45]:
l1.scores(1.3)

0.9903473815461346

In [48]:
sol = minimize_scalar(lambda x: np.abs(0.99 - l1.scores(x)), bounds = (0.0, 6.0), method="bounded")

In [49]:
sol

 message: Solution found.
 success: True
  status: 0
     fun: 0.00034738154613456196
       x: 1.3000274979692779
     nit: 15
    nfev: 15

In [50]:
sol.x

1.3000274979692779

In [56]:
xs = np.linspace(0.0, 3.0, 201)

In [58]:
px.scatter(x = xs, y = l1.scores(xs), log_y=True)

In [32]:
0.99 - l1.scores(l1.threshold)

-0.010000000000000009

In [29]:
l1.threshold

19.99999335625205

In [28]:
l1.error_matrix

array([[1., 1.],
       [0., 0.]])

In [104]:
l1([400*10,     10])

array([[3936,    3],
       [  63,    6]])

In [67]:
4010 / 69

58.11594202898551

In [65]:
l1.error_matrix

array([[0.98409371, 0.38072391],
       [0.01590629, 0.61927609]])