In [1]:
from classifier import *

In [2]:
import plotly.express as px

In [3]:
# dummy classifier test

In [4]:
dc = DummyClassifier()
dc([600, 400])

array([[  0,   0],
       [600, 400]])

In [5]:
# gaussian classifier test

In [6]:
gc = GaussianClassifier(99 / 100, 3.0)

In [7]:
gc([1000, 10])

array([[996,   3],
       [  3,   6]])

In [8]:
gc.threshold

2.669043039901781

In [9]:
gc.tn

0.9961966148977294

In [10]:
gc.fp

0.003803385102270629

In [11]:
gc.fn

0.37033849802260643

In [12]:
gc.error_matrix

array([[0.99619661, 0.3703385 ],
       [0.00380339, 0.6296615 ]])

In [13]:
o = gc([1000, 100])

In [14]:
o

array([[999,  89],
       [  0,  10]])

In [15]:
get_rejected(o)

array([999,  89])

In [16]:
get_passed(o)

array([ 0, 10])

In [17]:
# L1T test

In [18]:
l1 = L1TClassifier(99/100)

/Users/wilkie/code/system_flow/classifier.py:204: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [19]:
l1.egamma_l

0.02585292794736181

In [20]:
l1.jet_l

0.0021968083767679625

In [21]:
l1.muon_l

0.04166357056582804

In [22]:
l1.tau_l

0.01586962977254491

In [23]:
l1.null_samples

array([[[7.38321781e+01, 8.98061125e+00, 1.30110714e+01, 2.82003744e+01],
        [0.00000000e+00, 1.77084687e-02, 1.52541114e-02, 8.61218375e-02]],

       [[1.88819461e+02, 6.23871087e+00, 2.82712988e+01, 3.13418926e+01],
        [1.37447122e-02, 5.10309881e-03, 1.27321836e-01, 1.42321530e-01]],

       [[3.90860906e+01, 6.84284900e+00, 1.80192675e+01, 8.32291441e-01],
        [0.00000000e+00, 7.33374862e-03, 1.93271333e-02, 1.98176563e-05]],

       ...,

       [[6.21509816e+01, 1.52443540e+01, 2.52689600e+01, 1.65284666e+01],
        [0.00000000e+00, 2.90873962e-01, 3.26329156e-02, 1.47533294e-02]],

       [[1.80703737e+02, 6.90518476e+00, 1.33136461e+01, 1.31630945e+01],
        [8.11212037e-03, 7.57937435e-03, 1.57328366e-02, 9.39334408e-03]],

       [[1.12644614e+02, 6.74671714e+00, 1.26249998e+01, 8.63095874e+00],
        [0.00000000e+00, 6.96022606e-03, 1.45430371e-02, 4.01872905e-03]]])

In [24]:
l1.pos_samples

array([[[1.55319994e+02, 1.01193931e+02, 6.98039188e+00, 2.54725435e+01],
        [6.16855486e-04, 9.36199799e-01, 1.97667953e-03, 5.49934222e-02]],

       [[1.71630992e+02, 4.05157991e+00, 4.24913444e+01, 2.41206131e+01],
        [2.87752009e-03, 1.96699084e-04, 9.43065354e-01, 4.32333692e-02]],

       [[3.95196518e+02, 3.79414717e+00, 8.93742813e+01, 1.77628168e+01],
        [9.88707492e-01, 4.46357164e-05, 9.79744131e-01, 1.70015468e-02]],

       ...,

       [[2.08169768e+01, 1.21258645e+00, 5.42787044e+01, 2.72314580e+01],
        [0.00000000e+00, 5.37048892e-03, 9.63350754e-01, 7.53039846e-02]],

       [[8.68328409e+02, 4.47307466e+01, 4.30461999e+01, 8.79234801e+01],
        [9.93819530e-01, 9.43279901e-01, 9.44438340e-01, 9.92812737e-01]],

       [[1.25047449e+02, 2.37162656e+00, 3.18820570e+01, 2.96367575e+00],
        [0.00000000e+00, 1.29561243e-03, 7.53454864e-01, 4.29172177e-04]]])

In [25]:
from scipy.stats import permutation_test

In [26]:
nz = np.sum(l1.null_samples[:,1,:], axis=1)

In [27]:
pz = np.sum(l1.pos_samples[:,1,:], axis=1)

In [28]:
px.histogram(nz)

In [29]:
px.histogram(pz)

In [30]:
t = np.reshape(pz, (1, -1)) > np.reshape(nz, (-1,1))

In [31]:
t.shape

(10000, 10000)

In [32]:
np.mean(t)

0.97598791

In [33]:
def order_test(null_samples, pos_samples):
    score = lambda x: np.sum(x[:,1,:], axis=1)
    null_scores = score(null_samples)
    pos_scores = score(pos_samples)

    p = np.mean(np.reshape(pos_scores, (1, -1)) > np.reshape(null_scores, (-1,1)))
    error = 1 - p
    confusion = np.array([[p, error], [error, p]])

    return confusion

In [34]:
order_test(l1.null_samples, l1.pos_samples)

array([[0.97598791, 0.02401209],
       [0.02401209, 0.97598791]])

In [35]:
l1([39992495,     7504])

array([[39032191,      180],
       [  960303,     7323]])

In [36]:
l1.error_matrix

array([[0.97598791, 0.02401209],
       [0.02401209, 0.97598791]])