In [1]:
from classifier import *

In [2]:
# dummy classifier test

In [3]:
dc = DummyClassifier()
dc([600, 400])

array([[  0.,   0.],
       [600., 400.]])

In [4]:
# gaussian classifier test

In [5]:
gc = GaussianClassifier(0.01, 3.0, inputs=[1000, 10])

In [6]:
gc.threshold

2.6690430399017817

In [7]:
gc.tn

0.9961966148977294

In [8]:
gc.fp

0.003803385102270629

In [9]:
gc.fn

0.37033849802260677

In [10]:
gc.error_matrix

array([[0.99619661, 0.3703385 ],
       [0.00380339, 0.6296615 ]])

In [11]:
gc([1000, 100]).astype("int")

array([[996,  37],
       [  3,  62]])

In [12]:
# L1T test

In [13]:
l1 = L1TClassifier(1/100)

/Users/wilkie/code/system_flow/classifier.py:205: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [14]:
l1.egamma_l

0.02585292794736181

In [15]:
l1.jet_l

0.0021968083767679625

In [16]:
l1.muon_l

0.04166357056582804

In [17]:
l1.tau_l

0.01586962977254491

In [18]:
l1.error_matrix

array([[0.99361638, 0.63836164],
       [0.00638362, 0.36163836]])