In [1]:
from classifier import *

In [2]:
import plotly.express as px

In [3]:
# dummy classifier test

In [4]:
dc = DummyClassifier()
dc([600, 400], 1.0)

array([[  0,   0],
       [600, 400]])

In [5]:
# gaussian classifier test

In [6]:
gc = GaussianClassifier(3.0)

In [7]:
gc([1000, 10], 0.99)

array([[996,   3],
       [  3,   6]])

In [8]:
gc.threshold

2.669041266209834

In [9]:
gc.tn

0.9961965948124544

In [10]:
gc.fp

0.0038034051875456276

In [11]:
gc.fn

0.3703378281326751

In [12]:
gc.error_matrix

array([[0.99619659, 0.37033783],
       [0.00380341, 0.62966217]])

In [13]:
o = gc([1000, 100], 0.99)

In [14]:
o

array([[999,  89],
       [  0,  10]])

In [15]:
get_rejected(o)

array([999,  89])

In [16]:
get_passed(o)

array([ 0, 10])

In [17]:
# L1T test

In [18]:
l1 = L1TClassifier()

/Users/wilkie/code/system_flow/classifier.py:200: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  fit = lambda l: np.abs(self.egamma_rate - quad(lambda x: self.exp_dist(x, l) * interpolator(x), np.min(xs), np.max(xs))[0])


In [19]:
l1.egamma_l

0.02585292794736181

In [20]:
l1.jet_l

0.0021968083767679625

In [21]:
l1.muon_l

0.04166357056582804

In [22]:
l1.tau_l

0.01586962977254491

In [23]:
l1.null_samples

array([[[1.46697251e+02, 1.51054542e+01, 2.52416383e-01, 1.52467111e+01],
        [2.54758792e-04, 2.82632801e-01, 0.00000000e+00, 1.25777939e-02]],

       [[2.13420805e+02, 8.82639908e+00, 1.30988150e+01, 2.69245633e+01],
        [4.05376353e-02, 1.66598215e-02, 1.54008179e-02, 7.19388965e-02]],

       [[1.64489522e+02, 1.08094879e+01, 2.74432479e+01, 2.69499617e+01],
        [1.17483385e-03, 4.13791355e-02, 8.32766722e-02, 7.22208716e-02]],

       ...,

       [[1.72523695e+02, 3.68324072e+00, 1.46574203e+01, 1.83722016e+01],
        [3.27477803e-03, 1.21144797e-05, 1.71821117e-02, 1.81661790e-02]],

       [[1.22548409e+02, 6.78421129e-02, 1.75437031e+01, 2.78270259e+01],
        [0.00000000e+00, 1.25941239e-02, 1.90980993e-02, 8.18152712e-02]],

       [[5.66529888e+01, 1.20374095e+01, 5.32298103e+00, 4.92127713e+00],
        [0.00000000e+00, 1.02247710e-01, 6.25472526e-05, 1.26395070e-03]]])

In [24]:
l1.pos_samples

array([[[8.03875583e+01, 9.97721225e+00, 1.82619475e+01, 9.39636576e+01],
        [0.00000000e+00, 2.72901480e-02, 1.94439322e-02, 9.93547914e-01]],

       [[3.03507758e+02, 4.62391141e+01, 1.16360746e+02, 1.96958404e+01],
        [6.93937431e-01, 9.44120610e-01, 9.83371526e-01, 2.08188709e-02]],

       [[6.70517914e+02, 6.37397190e+01, 4.44154173e+00, 3.46485567e+00],
        [9.93819530e-01, 9.42046856e-01, 0.00000000e+00, 6.01429480e-04]],

       ...,

       [[2.66296252e+02, 4.35043226e+01, 1.61505458e+01, 1.77769976e+01],
        [2.68004906e-01, 9.43279901e-01, 1.82940950e-02, 1.70282396e-02]],

       [[3.24807266e+02, 2.82260091e+00, 3.97079350e+00, 1.65541757e+01],
        [8.81570843e-01, 4.87894104e-04, 0.00000000e+00, 1.47986312e-02]],

       [[3.01232703e+02, 2.06010663e+01, 2.38999176e+01, 4.76272892e+01],
        [6.67222474e-01, 7.13913117e-01, 2.48150624e-02, 8.54305025e-01]]])

In [25]:
n_ecdf = ecdf(l1.null_scores)

In [26]:
n_ecdf.cdf.evaluate(0.26)

array(0.5527)

In [27]:
l1.solve_reduction([4000, 10], 0.99)  

In [28]:
from scipy.stats import gaussian_kde

In [29]:
from scipy.integrate import cumulative_trapezoid

In [30]:
px.histogram(x = l1.pos_scores)

In [31]:
pos_kde = gaussian_kde(l1.pos_scores)

In [32]:
xpts = np.linspace(0.0, 5.0, 1001)
ypts = pos_kde.evaluate(xpts)
ycdf = cumulative_trapezoid(ypts, xpts, initial=0)
px.scatter(x = xpts, y = ypts)

In [33]:
px.scatter(x = xpts, y = ycdf)

In [34]:
px.histogram(x = l1.null_scores)

In [35]:
neg_kde = gaussian_kde(l1.null_scores)

In [36]:
xpts = np.linspace(0.0, 5.0, 1001)
ypts = neg_kde.evaluate(xpts)
ycdf = cumulative_trapezoid(ypts, xpts, initial=0)
px.scatter(x = xpts, y = ypts)

In [37]:
xpts = np.linspace(0.0, 4.2, 1001)
px.scatter(x = xpts, y = ycdf)

In [38]:
l1.threshold

1.333150029150187

In [39]:
l1.error_matrix

array([[0.9909, 0.627 ],
       [0.0091, 0.373 ]])

In [40]:
l1.skill_boost = 5.0

In [41]:
l1.solve_reduction([4000, 10], 0.99)  

In [42]:
l1.threshold

1.3604439060796318

In [43]:
l1.error_matrix

array([[0.9925, 0.    ],
       [0.0075, 1.    ]])

In [44]:
hlt = HLTClassifier()

/Users/wilkie/code/system_flow/classifier.py:424: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [51]:
hlt.solve_reduction([1000, 10], 0.99)

In [52]:
hlt.error_matrix

array([[1.    , 0.1916],
       [0.    , 0.8084]])

In [53]:
get_passed(hlt.error_matrix)

array([0.    , 0.8084])

In [54]:
get_rejected(hlt.error_matrix)

array([1.    , 0.1916])