In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar
from scipy.interpolate import PchipInterpolator
from scipy.integrate import quad
from scipy.stats import bootstrap
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

# Level-1 Trigger (CMS)

In [2]:
egamma = pd.read_csv("l1t_data/egamma.csv")
tau = pd.read_csv("l1t_data/isolated tau.csv")
jet_energy = pd.read_csv("l1t_data/jet energy.csv")
muon = pd.read_csv("l1t_data/single muon.csv")

In [3]:
rates = pd.read_excel("l1t_data/trigger_rates.xlsx")

In [4]:
triggers = ["Jet", "Muon", "EGamma", "Tau"]
rejection_ratio = 400
jet_rate = rates["Jet Rate"][0] 
muon_rate = rates["Muon Rate"][0] 
egamma_rate = rates["Egamma Rate"][0] 
tau_rate = rates["Tau Rate"][0] 
all_rates = [jet_rate, muon_rate, egamma_rate, tau_rate]

In [5]:
fig = go.Figure()
fig.add_bar(x = triggers, y = all_rates)
fig.update_layout(width = 800, height = 600)

In [6]:
exp_dist = lambda x, l: l * np.exp(-1 * l * x) * (x > 0)

In [7]:
exp_cdf = lambda x, l: 1 - np.exp(-l * x)

In [8]:
exp_generator = lambda p, l: (-1 / l) * np.log(1 - p)

In [9]:
xs = np.linspace(0.01, 5.0, 101)
fig = go.Figure()
fig.add_scatter(x = xs, y = exp_dist(xs, 1.5), name = "PDF")
fig.add_scatter(x = xs, y = exp_cdf(xs, 1.5), name = "CDF")
fig.update_layout(width = 800, height = 600)

In [10]:
data_range = lambda x: np.linspace(np.min(x), np.max(x), 101)

In [11]:
egamma_spl = PchipInterpolator(egamma["x"], egamma[" y"])

In [12]:
egamma_xs = data_range(egamma["x"])

In [13]:
egamma_rate

0.444

# Fit to EGamma L1T

In [14]:
#fit to muon - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
egamma_fit = lambda l: np.abs(egamma_rate - quad(lambda x: exp_dist(x, l) * egamma_spl(x), np.min(egamma_xs), np.max(egamma_xs))[0])

In [15]:
egamma_soln = minimize_scalar(egamma_fit, bounds = [0.00, 0.40], method="bounded")
egamma_l = egamma_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_38929/3527769200.py:2: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [16]:
egamma_soln

     fun: 1.6358825408624433e-05
 message: 'Solution found.'
    nfev: 18
     nit: 18
  status: 0
 success: True
       x: 0.02585292794736181

In [17]:
egamma_threshold = 30
egamma_ideal = lambda x: 1.0 * (x > egamma_threshold)

In [18]:
fig = go.Figure()
fig.add_scatter(x = egamma["x"], y = egamma[" y"], name="Data")
fig.add_scatter(x = egamma_xs, y = egamma_spl(egamma_xs), name="Interpolation")
fig.add_scatter(x = egamma_xs, y = egamma_ideal(egamma_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = egamma_xs, y = 1.0 - exp_cdf(egamma_xs, egamma_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "e-gamma L1T efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )
fig.update_xaxes(type = "log")

In [19]:
fig = go.Figure()
fig.add_scatter(x = egamma["x"], y = egamma[" y"], name="Data")
fig.add_scatter(x = egamma_xs, y = egamma_spl(egamma_xs), name="Interpolation")
fig.add_scatter(x = egamma_xs, y = egamma_ideal(egamma_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = egamma_xs, y = 1.0 - exp_cdf(egamma_xs, egamma_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "e-gamma L1T efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )


## Fit to Tau 

In [20]:
tau_xs = data_range(tau["x"])
tau_spl = PchipInterpolator(tau["x"], tau[" y"])

In [21]:
#fit to tau - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
tau_fit = lambda l: np.abs(tau_rate - quad(lambda x: exp_dist(x, l) * tau_spl(x), 0, 100)[0])

In [22]:
tau_threshold = 38
tau_ideal = lambda x: 1.0 * (x > tau_threshold)

In [23]:
tau_soln = minimize_scalar(tau_fit)
tau_l = tau_soln.x

In [24]:
tau_soln

     fun: 1.378231251347728e-09
 message: '\nOptimization terminated successfully;\nThe returned value satisfies the termination criteria\n(using xtol = 1.48e-08 )'
    nfev: 35
     nit: 31
 success: True
       x: 0.04457408261926413

In [25]:
tau_l

0.04457408261926413

In [26]:
fig = go.Figure()
fig.add_scatter(x = tau["x"], y = tau[" y"], name = "Data")
fig.add_scatter(x = tau_xs, y = tau_spl(tau_xs), name = "Interpolation")
fig.add_scatter(x = tau_xs, y = tau_ideal(tau_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = tau_xs, y = 1.0 - exp_cdf(tau_xs, tau_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Tau L1T Efficiency",
                  xaxis_title = "Momentum (GeV)",
                  yaxis_title = "Efficiency",
                  )
fig.update_xaxes(type = "linear")

## Fit to Jets

In [27]:
jet_xs = data_range(jet_energy["x"])
jet_spl = PchipInterpolator(jet_energy["x"], jet_energy[" y"])

In [28]:
jet_fit = lambda l: np.abs(jet_rate - quad(lambda x: exp_dist(x, l) * jet_spl(x), 0, np.max(jet_xs))[0])
jet_soln = minimize_scalar(jet_fit, bounds = [0.000, 0.40], method="bounded")
jet_l = jet_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_38929/2457454635.py:1: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [29]:
jet_soln

     fun: 0.00010411688622924409
 message: 'Solution found.'
    nfev: 19
     nit: 19
  status: 0
 success: True
       x: 0.0034652456666858103

In [30]:
jet_l

0.0034652456666858103

In [31]:
jet_threshold = 320
jet_ideal = lambda x: 1.0 * (x > jet_threshold)

In [32]:
fig = go.Figure()
fig.add_scatter(x = jet_energy["x"], y = jet_energy[" y"], name = "Data")
fig.add_scatter(x = jet_xs, y = jet_spl(jet_xs), name = "Interpolation")
fig.add_scatter(x = jet_xs, y = jet_ideal(jet_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = jet_xs, y = 1.0 - exp_cdf(jet_xs, jet_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Jet Energy L1T Efficiency",
                  xaxis_title = "Momentum (GeV)"
                  )
fig.update_xaxes(type = "linear")

## Fit to Muon

In [33]:
muon_xs = data_range(muon["x"])
muon_spl = PchipInterpolator(muon["x"], muon[" y"])

In [85]:
#fit to muon - minimize the difference between the trigger efficiency multiplied by the underlying distribution and the trigger rate
muon_fit = lambda l: np.abs(muon_rate - quad(lambda x: exp_dist(x, l) * muon_spl(x), 0, np.max(muon_xs))[0])
muon_soln = minimize_scalar(muon_fit, bounds = [0.00, 0.100], method="bounded")
muon_l = muon_soln.x

/var/folders/qc/b4ggx3516_qc8fy84rgtp36c0000gq/T/ipykernel_38929/1988843803.py:2: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.



In [86]:
muon_l

0.05513620525526383

In [87]:
muon_threshold = 22
muon_ideal = lambda x: 1.0 * (x > muon_threshold)

In [88]:
fig = go.Figure()
fig.add_scatter(x = muon["x"], y = muon[" y"], name = "data")
fig.add_scatter(x = muon_xs, y = muon_spl(muon_xs), name = "Interpolation")
fig.add_scatter(x = muon_xs, y = muon_ideal(muon_xs), name = "Ideal", line_dash="dash")
fig.add_scatter(x = muon_xs, y = 1.0 - exp_cdf(muon_xs, muon_l), name = "Data Fit")
fig.update_layout(width = 800,
                  height = 600,
                  title = "Single Muon L1T Efficiency",
                  xaxis_title = "Momentum (GeV)"
                  )
fig.update_xaxes(type = "linear")

# Modeling Skill

In [89]:
#find the percentile of measurements above threshold
egamma_prctile = exp_cdf(egamma_threshold, egamma_l)
jet_prctile = exp_cdf(jet_threshold, jet_l)
muon_prctile = exp_cdf(muon_threshold, muon_l)
tau_prctile = exp_cdf(tau_threshold, tau_l) 

In [90]:
thresholds = np.array([jet_threshold, muon_threshold, egamma_threshold, tau_threshold])

In [91]:
prctiles = np.array([jet_prctile, muon_prctile, egamma_prctile, tau_prctile])

In [92]:
prctiles

array([0.67007127, 0.70269494, 0.53956696, 0.8161831 ])

In [93]:
def generate_null():
    p = np.random.uniform(size=(4)) * prctiles
    jet = exp_generator(p[0], jet_l)
    muon = exp_generator(p[1], muon_l)
    egamma = exp_generator(p[2], egamma_l)
    tau = exp_generator(p[3], tau_l)
    

    e = np.array([jet, muon, egamma, tau])
    z = np.array([jet_spl(e[0]),
                muon_spl(e[1]),
                egamma_spl(e[2]),
                tau_spl(e[3])])
    
    res = np.stack((e, z))
    
    return res


In [94]:
null_evt = generate_null()

In [95]:
null_evts = np.stack([generate_null() for i in range(10000)])

In [96]:
null_evts.shape

(10000, 2, 4)

In [97]:
null_z = np.sum(null_evts, axis=2)[:,1]

In [98]:
px.histogram(x=null_z)

In [113]:
np.std(null_z)

0.2902596790424275

In [99]:
triggers

['Jet', 'Muon', 'EGamma', 'Tau']

In [100]:
prctiles

array([0.67007127, 0.70269494, 0.53956696, 0.8161831 ])

In [101]:
evt_rng = np.random.default_rng()

In [102]:
trigger_rates = rates["Proportion"]

In [103]:
trigger_choice = lambda: evt_rng.choice(np.arange(len(trigger_rates)), 1, p = trigger_rates)[0]

In [104]:
rates.iloc[trigger_choice()]

Percentage            11.500
Proportion             0.115
Jet / Jet energy       1.000
Muon                   0.000
Egamma                 0.000
Tau                    0.000
Jet proportions        0.115
Muon proportions       0.000
Egamma proportions     0.000
Tau proportions        0.000
Jet Rate                 NaN
Muon Rate                NaN
Egamma Rate              NaN
Tau Rate                 NaN
Name: 8, dtype: float64

In [105]:
def generate_positive():
    #select a trigger outcome with rates proportional to those recorded
    outcome_idx = trigger_choice()
    outcome = rates.iloc[outcome_idx]

    #determine the triggers for that outcome
    trig_egamma = outcome["Egamma"]
    trig_jet = outcome["Jet / Jet energy"]
    trig_muon = outcome["Muon"]
    trig_tau = outcome["Tau"]

    triggers = np.array([trig_jet, trig_muon, trig_egamma, trig_tau])

    #generate particle energies from the distributions based on whether or not they're above trigger levels
    def transform_p(prctile, outcome):
        p = np.random.uniform()
        if outcome == 1.0:
            #generate an event above the trigger threshold
            return p * (1 - prctile) + prctile
        else:
            #generate an event below the trigger threshold
            return p * prctile
        
    p_jet = transform_p(jet_prctile, trig_jet)
    p_muon = transform_p(muon_prctile, trig_muon)
    p_egamma = transform_p(egamma_prctile, trig_egamma)
    p_tau = transform_p(tau_prctile, trig_tau)

    jet = exp_generator(p_jet, jet_l)
    muon = exp_generator(p_muon, muon_l)
    egamma = exp_generator(p_egamma, egamma_l)
    tau = exp_generator(p_tau, tau_l)

    e = np.array([jet, muon, egamma,  tau,])
    z = np.array([jet_spl(e[0]),
                  muon_spl(e[1]),
                  egamma_spl(e[2]),
                  tau_spl(e[3]),
                  ])
    
    res = np.stack((e, z))
    
    return res


In [106]:
pos_evt = generate_positive()

In [107]:
pos_evt

array([[2.64844817e+02, 4.70573848e+00, 2.01254344e+01, 4.47595735e+01],
       [2.57056151e-01, 1.03329579e-03, 2.04965576e-02, 7.83597809e-01]])

In [108]:
thresholds

array([320,  22,  30,  38])

In [109]:
pos_evt[1,:]

array([0.25705615, 0.0010333 , 0.02049656, 0.78359781])

In [110]:
pos_evts = np.stack([generate_positive() for i in range(10000)])

In [111]:
pos_z = np.sum(pos_evts, axis=2)[:,1]

In [112]:
px.histogram(x=pos_z)

## determine statistics

In [114]:
from sklearn.svm import LinearSVC

In [115]:
classifier = LinearSVC()

In [123]:
x = np.concatenate([null_z, pos_z]).reshape(-1,1)

In [118]:
y = np.concatenate([np.zeros(null_z.shape), np.ones(pos_z.shape)])

In [125]:
classifier.fit(x, y)

LinearSVC()

In [134]:
null_z2 = classifier.decision_function(null_z.reshape(-1,1))

In [136]:
pos_z2 = classifier.decision_function(pos_z.reshape(-1,1))

In [139]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=null_z2))
fig.add_trace(go.Histogram(x=pos_z2))


In [126]:
classifier.score(x, y)

0.94945

In [62]:
bts_null = bootstrap((null_z,), np.mean)

In [63]:
np.mean(null_z)

0.5730385367313473

In [64]:
bts_null.standard_error

0.005619897794756606

In [65]:
bts_pos = bootstrap((pos_z,), np.mean)

/Users/wilkie/anaconda3/envs/jax/lib/python3.10/site-packages/scipy/stats/_resampling.py:92: DegenerateDataWarning:

The bootstrap distribution is degenerate; the confidence interval is not defined.



In [66]:
np.mean(pos_z)

nan

In [67]:
bts_pos.standard_error

nan